apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: demo-http
spec:
  type: NodePort
  selector:
    app: httpd-alpine
  ports:
    - protocol: TCP
      port: 8080        # service
      targetPort: 55555 # listening to port 80 of the selectered pod
      nodePort: 30001  # expose externally on host
      